Portfolio work section
brainconnect93/My-Portfolio pull request #2
Opened 2022-04-23 21:26 UTC by brainconnect93

I did this project by
1. checkout to a new branch (portfolio-work-section)
2. type my work section HTML code and giving it a befitting styling
3. type my about section HTML code and give it a befitting styling
4. rename some of the images as requested by linters
5. commit my work and push it to the branch

2022-04-23 23:16 UTC, omar-labana requested changes
Hi @brainconnect93, 

Excellent work so far! 👌
You have implemented almost all the required features without any errors or bugs. ✔️ 
There are some cases that you need to adjust but you are almost done! 😀

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
_N/A_

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-23 23:16 UTC, omar-labana commented on index.html
> +                    <p>let's connect</p>
- [ ] Let's update this `p` tag to be an `hx` tag, the purpose of the text included is a call for action more than being a paragraph text.

2022-04-23 23:16 UTC, omar-labana commented on index.html
> +<section class="about-section">
- [ ] This section has a fixed padding of `5.5rem` causing it break on small phone screens. kindly fix it so it's identical to the design.
![image](https://user-images.githubusercontent.com/33767951/164948978-4595b029-465e-467e-a04e-7f0b669e5169.png)

2022-04-23 23:16 UTC, omar-labana commented on index.html
> +            <div class="work-box1">
- [ ] Projects are kinda broken on the smallest mobile screen `320px`, there seems to be a fixed size for some elements, kindly fix it.
![image](https://user-images.githubusercontent.com/33767951/164948968-d4fc5343-3a00-48ad-a9da-772e41bc392d.png)

2022-04-26 08:52 UTC, thecodechaser approved these changes
## STATUS: APPROVED 🟢

## Hi @brainconnect93👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-03 21:40 UTC, OLIPLICHE reviewed
Hi TEAM, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project that contains an old Pull Request. Please Create a new Pull Request for a fresh review of this milestone

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-05-03 22:08 UTC, merged